### ISSUE TITLE
Выбор программы

### ISSUE THREAD

**Issue by camorazrushimoe** [digitalshop24/bbetter#11]
Надо добавить возможность привязки к пользователю одной из программ тренировок. 

Должно быть 3 программы тренировок:
- Домохозяйка
- Карьеристка
- Беззаботная

Далее у не оплаченного аккаунта нет блока с загрузкой инфы и фоток (Данная секция появится только в этом таске #12 ):
![image](https://cloud.githubusercontent.com/assets/8914398/16427799/c44a8826-3d77-11e6-9dd4-63e9a45dab0a.png)

А так же нет розового блока с тренировками:
![image](https://cloud.githubusercontent.com/assets/8914398/16427816/dea6a902-3d77-11e6-8f2f-dd87e72bbadf.png)

То есть розового блока нет вообще. 

Далее пользователь оплачивает аккаунт. После оплаты он видит блок с выбором программы:
![image](https://cloud.githubusercontent.com/assets/8914398/16427880/2a24b130-3d78-11e6-9cbb-ec0933e7a083.png)

Выбирает одну из программ, жмет "Начать". И у него появляется одна из выбранных им программ:
![image](https://cloud.githubusercontent.com/assets/8914398/16427912/4b35080c-3d78-11e6-9d9a-d2425f5e210e.png)

**Comment by kkan** [comment]
Сделал. Форму пока не вывожу вообще.
У плана тренировок с версткой что-то не так. + когда появляется план тренировок, выбираешь день и едет режим и питание
