### ISSUE TITLE
Загрузка фотографий + параметры человека

### ISSUE THREAD

**Issue by camorazrushimoe** [digitalshop24/bbetter#12]
Надо реализовать функционал загрузки фотографий и ввод параметров человека:
![image](https://cloud.githubusercontent.com/assets/8914398/16428327/046499e0-3d7a-11e6-911f-54afe0d9e246.png)

Данный блок появляется только у оплаченных аккаунтов. 

Кнопку "Еще" надо выпилисть, она больше не нужна.
![image](https://cloud.githubusercontent.com/assets/8914398/16430463/7e57bb1a-3d84-11e6-87bc-f7d88fafaf54.png)

Всего можно загрузить 6 фотографий. В каждом слайде по две фотографии. 

Текста вообще не должно быть:
![image](https://cloud.githubusercontent.com/assets/8914398/16430628/349d5164-3d85-11e6-8974-9943db52ee6d.png)

**Comment by camorazrushimoe** [comment]
@gitwhatislove на данный момент не готова загрузка фотографий

**Comment by kkan** [comment]
@gitwhatislove 
https://github.com/digitalshop24/bbetter/blob/staging/app/assets/javascripts/main.js#L127 перенеси это в profile.js
https://github.com/digitalshop24/bbetter/blob/staging/app/assets/javascripts/main.js#L233 - пофикси это (TypeError: $(...).live is not a function)

**Comment by kkan** [comment]
#65
