### ISSUE TITLE
Доработать формы обратной связи

### ISSUE THREAD

**Issue by camorazrushimoe** [digitalshop24/bbetter#21]
Необходимо доработать формы обратной связи. 

Форма в личном кабинете:
![image](https://cloud.githubusercontent.com/assets/8914398/16450145/258cac86-3e04-11e6-9065-58cd10518d7c.png)

Сообщения из этой формы попадают в админку. Но попадает только поле "сообщение" надо что бы еще отображалось и поле "Тема".

Форма на главной странице:
![image](https://cloud.githubusercontent.com/assets/8914398/16450173/4e2b68c6-3e04-11e6-9adc-7ad34afab797.png)

Сейчас эта форма это гугл док. Надо сделать что бы сообщения в эту форму так же попадали в админку. Предлагаю объединить обе эти формы в сообщения в админке.

**Comment by kkan** [comment]
#61
