### ISSUE TITLE
Верстка блок тренеры и рационы питания +мелкие фиксы

### ISSUE THREAD

**Issue by camorazrushimoe** [digitalshop24/bbetter#22]
Надо переверстать два блока
Тексты: https://docs.google.com/document/d/1s4uMw8MKGogSqf7IcABk8lNttrzS6XLTbXmA4SX8-30/edit
### Тренеры на главной

![image](https://cloud.githubusercontent.com/assets/8914398/16450213/9e17a8b8-3e04-11e6-8f54-24ddd03a0f00.png)
### Питание в ЛК

![image](https://cloud.githubusercontent.com/assets/8914398/16450258/d499b14c-3e04-11e6-9411-6648e69ec7d8.png)

Этот блок изменяется только в админке. и на данный момент доступен всем пользователям. На главной должен остаться старый блок про питание. 

Кнопочки должны быть в линию:
![image](https://cloud.githubusercontent.com/assets/8914398/16450333/fab9a12a-3e04-11e6-9ee2-d56489999756.png)

**Comment by AndreyFedarovich** [comment]
Сергей, не могу найти как нужно переделать карусель

**Comment by AndreyFedarovich** [comment]
# ыаываа

**Comment by camorazrushimoe** [comment]
@adFedorovich тут psd клавной страницы https://yadi.sk/d/XOnok-6isSrYr/%D0%91%D1%8B%D1%82%D1%8C%20%D0%BB%D1%83%D1%87%D1%88%D0%B5 
у тренеров стало больше текста
