### ISSUE TITLE
Отправка промокодов. 

### ISSUE THREAD

**Issue by camorazrushimoe** [digitalshop24/bbetter#38]
Нужен функционал привязки промокодов к оплаченному аккаунту. 

Когда пользователь оплачивает аккаунт больше чем на 1 человека. Аккаунт должен не просто активироваться, но к аккаунту должны еще привязываться промокоды. Которые пользователь сможет отправить друзьям. 

Так же в выпадающем меню должна появится кнопка "Промокоды"

в этом меню:
![image](https://cloud.githubusercontent.com/assets/8914398/16493166/2115a0ce-3eed-11e6-9622-ae54665fd312.png)

При клике по этой кнопке попадаем на страницу:
http://staging.bbetter.club/promo

![image](https://cloud.githubusercontent.com/assets/8914398/16493188/38f677fe-3eed-11e6-91a3-87baf01d2721.png)

Если оплатили аккаунт на 2 человека. То видим 1 промокод. 
![image](https://cloud.githubusercontent.com/assets/8914398/16493198/442cd906-3eed-11e6-8ac5-e488b4b87109.png)

Если на 5 человек, то видим 4 промокода. Далее эти промокоды можно отправить другим пользователям на эмеил или телефон.

При клике "Пригласить" появляется попап в котором пользователь может указать телефон или эмеил:
![image](https://cloud.githubusercontent.com/assets/8914398/16493234/6af8f29a-3eed-11e6-8a35-23a7df790e3d.png)

После отправки в попапе должно появиться сообщение "Приглашение успешно отправлено"

Текст приглашений:
Эмеил:
№имя пользователя№ приглашает Вас зарегистрироваться на сайте bbetter.club
Нельзя вернуться в прошлое и изменить свой старт, но можно стартовать сейчас и изменить свой финиш.
Регистрируйтесь на сайте: http://bbetter.club
Ваш промокод: $$$$ 

СМС:
№Имя пользователя№ приглашает зарегистрироваться в bbetter.club Ваш промо-код: 59595955

После того как новый пользователь зарегистрируется и введет промокод, данные в этой таблице должны измениться на актуальные:
![image](https://cloud.githubusercontent.com/assets/8914398/16493504/63b78234-3eee-11e6-9099-4bc1e99c076e.png)

**Comment by camorazrushimoe** [comment]
Кнопка "Промокоды" должна появляться только у тех. аккаунтов у кого есть промокоды (или были). Так же надо переименовать кнопку "Промокоды" в "Пригласить"

Добавил к своему аккаунту тариф, в итоге не вижу промокоды:
![image](https://cloud.githubusercontent.com/assets/8914398/16563892/424fad70-420d-11e6-8d82-0ef7def918d0.png)

**Comment by camorazrushimoe** [comment]
Промокод не приходит на телефон.

Кнопка "промокоды" должна быть доступна только у тех. у кого есть или были промокоды:
![image](https://cloud.githubusercontent.com/assets/8914398/16582571/5a101d86-42b8-11e6-8515-165190502355.png)

**Comment by kkan** [comment]
#92
