### ISSUE TITLE
Доп.поля в попап регистрации

### ISSUE THREAD

**Issue by camorazrushimoe** [digitalshop24/bbetter#40]
В поп апе регистрации надо добавить дополнительное текстовое поле "Цель"
![image](https://cloud.githubusercontent.com/assets/8914398/16485628/a516f0d2-3ec8-11e6-8bc4-efe5d674afa8.png)

Так же надо добавить доп. поле "Номер телефона". 

Итого добавляем два поля:
- Цель
- Номер телефона

**Comment by kkan** [comment]
@v-kabashnikov номер телефона и цель валидируются как емэйл
