### ISSUE TITLE
Регистрация/редактирование профиля

### ISSUE THREAD

**Issue by camorazrushimoe** [digitalshop24/bbetter#5]
Должна работать регистрация на сайте:
![image](https://cloud.githubusercontent.com/assets/8914398/16422047/adfdeda0-3d5f-11e6-9da9-29fe7b70daf8.png)

Так же в попапе должен работать ввод промокода. Введенный промокод активирует тариф "Спортсмен одиночка". 

После регистрации пользователь попадает в личный кабинет. 

Должны работать эти кнопки:
![image](https://cloud.githubusercontent.com/assets/8914398/16427945/6bedcd0e-3d78-11e6-9886-4885050b75fe.png)

При клике на кнопку "Редактировать" должен открываться поп ап в котором можно отредактировать данные и нажать кнопку "Сохранить". Такой же поп ап как и при регистрации:
![image](https://cloud.githubusercontent.com/assets/8914398/16428077/e6fbb5e2-3d78-11e6-8a1a-198deb5b1d5c.png)

Но кнопка "Сохранить" и нет текста ожидайте письмо. 

Так же должно работать восстановление пароля:
**Тут картинка с полем для ввода эмеила (Это попап)**

При вводе эмеила, новый пароль отправляется на почту. В окне пишется "Ваш новый пароль отправлен на почту".

ВАЖНО! Обработка ошибок. При регистрации, редактировании профиля или восстановлении проля. Могут возникать ошибки. Эти ошибки должны отображаться в самой форме/поп апе. что бы верстальщик смог их стилизовать.

**Comment by kkan** [comment]
#25 #27 #31 #44

**Comment by kkan** [comment]
Нужно еще стилизовать информационные сообщения: https://github.com/digitalshop24/bbetter/blob/staging/app/views/users/_errors.html.erb#L13

**Comment by camorazrushimoe** [comment]
@adFedorovich стилизуешь сообщения?

**Comment by camorazrushimoe** [comment]
@adFedorovich готово?
