### ISSUE TITLE
Аккаунт с промокодом

### ISSUE THREAD

**Issue by camorazrushimoe** [digitalshop24/bbetter#56]
Ввел промокод, в результате мой аккаунт не стал оплаченным:
![image](https://cloud.githubusercontent.com/assets/8914398/16517839/4012e1e4-3f88-11e6-84c8-85be4065c51c.png)

Так же видны тарифы:
![image](https://cloud.githubusercontent.com/assets/8914398/16517847/49f2bc70-3f88-11e6-9dcb-fcb98f2f6ce8.png)

При этом промокод активирован:
![image](https://cloud.githubusercontent.com/assets/8914398/16517852/52d6f694-3f88-11e6-96fa-7d04d091e216.png)

**Comment by kkan** [comment]
@camorazrushimoe ну не знаю, только что зарегался - все норм. попробуй еще раз ошибку воспроизвести

**Comment by camorazrushimoe** [comment]
это я в общем активирован аккаунт через промокод. А потом вручную удалил оплаченный тариф.
