### ISSUE TITLE
Эмеил рассылка

### ISSUE THREAD

**Issue by camorazrushimoe** [digitalshop24/bbetter#67]
Шаблон рассылки:
[Archive.zip](https://github.com/digitalshop24/bbetter/files/346310/Archive.zip)

Надо запустить эту рассылку по всем зарегистрированным пользователям. 

Кнопочки:
![image](https://cloud.githubusercontent.com/assets/8914398/16560988/6ada53f2-41ff-11e6-9363-77184c879633.png)

Это должны быть ссылки на оплату соответствующего тарифа. (Сразу на яндекс кассу)

Надо написать почту получателя:
![image](https://cloud.githubusercontent.com/assets/8914398/16561008/88d288ca-41ff-11e6-9381-939e74151c34.png)

По кнопке "Отказаться" человек попадает на страницу где написано что он отказался от рассылок.
![image](https://cloud.githubusercontent.com/assets/8914398/16561023/9ada29ec-41ff-11e6-97cf-41ca8fd2f51f.png)

Надо в профиле пользователя поставить маркер что он описался.

**Comment by kkan** [comment]
Здесь от меня значит ничего не требуется?
